/**
 * Curated Lucide icon library for the presentation editor.
 * Each entry pairs a display name (for search) with the Lucide component.
 */

import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  Briefcase,
  Brush,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDot,
  Clock,
  Cloud,
  Code,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Eye,
  EyeOff,
  Feather,
  File,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gift,
  Globe,
  Grid,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Info,
  Key,
  Layers,
  Layout,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  Mountain,
  MousePointer2,
  MoveRight,
  Music,
  Package,
  Palette,
  Paperclip,
  PauseCircle,
  Phone,
  PieChart,
  PlayCircle,
  Plus,
  Printer,
  Puzzle,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Type,
  Unlock,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  Wifi,
  Wind,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface IconEntry {
  /** Lowercase searchable name; matches the Lucide export. */
  name: string;
  /** Search keywords in addition to the name. */
  keywords: string;
  /** Lucide component. */
  Component: LucideIcon;
}

export const ICON_LIBRARY: IconEntry[] = [
  // Core UI
  { name: "home",           keywords: "house building",              Component: Home },
  { name: "user",           keywords: "person profile",              Component: User },
  { name: "users",          keywords: "team group people",           Component: Users },
  { name: "settings",       keywords: "gear config",                 Component: Settings },
  { name: "search",         keywords: "find magnifier",              Component: Search },
  { name: "mail",           keywords: "email envelope",              Component: Mail },
  { name: "bell",           keywords: "notification alert",          Component: Bell },
  { name: "calendar",       keywords: "date schedule",               Component: Calendar },
  { name: "clock",          keywords: "time",                        Component: Clock },
  { name: "timer",          keywords: "duration stopwatch",          Component: Timer },
  { name: "map-pin",        keywords: "location pin geo",            Component: MapPin },
  { name: "compass",        keywords: "direction navigate",          Component: Compass },

  // Content
  { name: "file",           keywords: "document",                    Component: File },
  { name: "file-text",      keywords: "document page",               Component: FileText },
  { name: "folder",         keywords: "directory",                   Component: Folder },
  { name: "image",          keywords: "picture photo",               Component: ImageIcon },
  { name: "video",          keywords: "film movie",                  Component: Video },
  { name: "music",          keywords: "audio note",                  Component: Music },
  { name: "mic",            keywords: "microphone record",           Component: Mic },
  { name: "camera",         keywords: "photo capture",               Component: Camera },
  { name: "paperclip",      keywords: "attach",                      Component: Paperclip },
  { name: "archive",        keywords: "box storage",                 Component: Archive },
  { name: "printer",        keywords: "print",                       Component: Printer },

  // Communication
  { name: "message-square", keywords: "chat comment",                Component: MessageSquare },
  { name: "message-circle", keywords: "chat bubble",                 Component: MessageCircle },
  { name: "phone",          keywords: "call",                        Component: Phone },
  { name: "send",           keywords: "deliver",                     Component: Send },
  { name: "share",          keywords: "share out",                   Component: Share2 },

  // Commerce
  { name: "shopping-bag",   keywords: "store",                       Component: ShoppingBag },
  { name: "shopping-cart",  keywords: "checkout",                    Component: ShoppingCart },
  { name: "credit-card",    keywords: "payment",                     Component: CreditCard },
  { name: "wallet",         keywords: "money",                       Component: Wallet },
  { name: "dollar-sign",    keywords: "price money currency",        Component: DollarSign },
  { name: "tag",            keywords: "label price",                 Component: Tag },
  { name: "package",        keywords: "box parcel",                  Component: Package },
  { name: "gift",           keywords: "present reward",              Component: Gift },
  { name: "truck",          keywords: "delivery shipping",           Component: Truck },

  // Status & feedback
  { name: "check",          keywords: "done tick confirm",           Component: Check },
  { name: "check-circle",   keywords: "success confirm",             Component: CheckCircle },
  { name: "x",              keywords: "close cancel dismiss",        Component: X },
  { name: "x-circle",       keywords: "error fail",                  Component: XCircle },
  { name: "alert-triangle", keywords: "warning",                     Component: AlertTriangle },
  { name: "alert-circle",   keywords: "warning attention",           Component: AlertCircle },
  { name: "info",           keywords: "information help",            Component: Info },
  { name: "help-circle",    keywords: "question",                    Component: HelpCircle },

  // Data & analytics
  { name: "bar-chart",      keywords: "chart graph stats",           Component: BarChart3 },
  { name: "pie-chart",      keywords: "chart stats",                 Component: PieChart },
  { name: "line-chart",     keywords: "chart graph trend",           Component: LineChart },
  { name: "trending-up",    keywords: "growth increase",             Component: TrendingUp },
  { name: "trending-down",  keywords: "decline decrease",            Component: TrendingDown },
  { name: "activity",       keywords: "pulse live",                  Component: Activity },
  { name: "zap",            keywords: "lightning fast",              Component: Zap },
  { name: "database",       keywords: "data storage",                Component: Database },
  { name: "filter",         keywords: "sort",                        Component: Filter },

  // Actions
  { name: "plus",           keywords: "add create new",              Component: Plus },
  { name: "minus",          keywords: "subtract remove",             Component: Minus },
  { name: "edit",           keywords: "pencil write",                Component: Edit },
  { name: "trash",          keywords: "delete remove",               Component: Trash2 },
  { name: "copy",           keywords: "duplicate",                   Component: Copy },
  { name: "download",       keywords: "save off",                    Component: Download },
  { name: "upload",         keywords: "send up",                     Component: Upload },
  { name: "save",           keywords: "persist disk",                Component: Save },
  { name: "refresh",        keywords: "reload sync",                 Component: RefreshCw },
  { name: "lock",           keywords: "secure private",              Component: Lock },
  { name: "unlock",         keywords: "open public",                 Component: Unlock },
  { name: "eye",            keywords: "view show",                   Component: Eye },
  { name: "eye-off",        keywords: "hide",                        Component: EyeOff },
  { name: "key",            keywords: "access unlock",               Component: Key },
  { name: "shield",         keywords: "security protect",            Component: ShieldCheck },

  // Tech
  { name: "code",           keywords: "developer programming",       Component: Code },
  { name: "terminal",       keywords: "cli console",                 Component: Terminal },
  { name: "cpu",            keywords: "processor chip",              Component: Cpu },
  { name: "wifi",           keywords: "wireless signal",             Component: Wifi },
  { name: "cloud",          keywords: "storage weather",             Component: Cloud },
  { name: "server",         keywords: "backend rack",                Component: Server },
  { name: "globe",          keywords: "world internet",              Component: Globe },
  { name: "link",           keywords: "url hyperlink",               Component: Link },
  { name: "link2",          keywords: "chain",                       Component: Link2 },
  { name: "smartphone",     keywords: "mobile phone",                Component: Smartphone },
  { name: "monitor",        keywords: "screen display",              Component: Monitor },
  { name: "puzzle",         keywords: "piece integrate",             Component: Puzzle },

  // Creative / design
  { name: "palette",        keywords: "color art",                   Component: Palette },
  { name: "brush",          keywords: "paint",                       Component: Brush },
  { name: "sparkles",       keywords: "magic ai shine",              Component: Sparkles },
  { name: "layers",         keywords: "stack depth",                 Component: Layers },
  { name: "grid",           keywords: "layout",                      Component: Grid },
  { name: "layout",         keywords: "template",                    Component: Layout },
  { name: "type",           keywords: "text font",                   Component: Type },
  { name: "hash",           keywords: "number tag",                  Component: Hash },
  { name: "circle-dot",     keywords: "target bullet",               Component: CircleDot },
  { name: "mouse-pointer",  keywords: "click cursor",                Component: MousePointer2 },

  // Arrows
  { name: "arrow-right",    keywords: "next forward",                Component: ArrowRight },
  { name: "arrow-left",     keywords: "back previous",               Component: ArrowLeft },
  { name: "arrow-up",       keywords: "up rise",                     Component: ArrowUp },
  { name: "arrow-down",     keywords: "down fall",                   Component: ArrowDown },
  { name: "arrow-up-right", keywords: "diagonal external",           Component: ArrowUpRight },
  { name: "chevron-right",  keywords: "caret next",                  Component: ChevronRight },
  { name: "chevron-left",   keywords: "caret back",                  Component: ChevronLeft },
  { name: "chevron-up",     keywords: "caret up",                    Component: ChevronUp },
  { name: "chevron-down",   keywords: "caret down",                  Component: ChevronDown },
  { name: "move-right",     keywords: "continue",                    Component: MoveRight },

  // Nature / atmosphere
  { name: "leaf",           keywords: "eco plant",                   Component: Leaf },
  { name: "sun",            keywords: "light day bright",            Component: Sun },
  { name: "moon",           keywords: "night dark",                  Component: Moon },
  { name: "flame",          keywords: "fire hot",                    Component: Flame },
  { name: "droplet",        keywords: "water drop",                  Component: Droplet },
  { name: "wind",           keywords: "breeze air",                  Component: Wind },
  { name: "mountain",       keywords: "peak landscape",              Component: Mountain },
  { name: "tree",           keywords: "forest plant",                Component: TreePine },
  { name: "feather",        keywords: "light soft",                  Component: Feather },

  // Goals / emotion
  { name: "heart",          keywords: "love like",                   Component: Heart },
  { name: "star",           keywords: "favorite rating",             Component: Star },
  { name: "bookmark",       keywords: "save",                        Component: Bookmark },
  { name: "thumbs-up",      keywords: "like approve",                Component: ThumbsUp },
  { name: "award",          keywords: "medal badge",                 Component: Award },
  { name: "trophy",         keywords: "winner prize",                Component: Trophy },
  { name: "target",         keywords: "goal aim",                    Component: Target },
  { name: "lightbulb",      keywords: "idea insight",                Component: Lightbulb },
  { name: "rocket",         keywords: "launch startup",              Component: Rocket },
  { name: "flag",           keywords: "mark milestone",              Component: Flag },
  { name: "briefcase",      keywords: "work business",               Component: Briefcase },
  { name: "play",           keywords: "start video",                 Component: PlayCircle },
  { name: "pause",          keywords: "stop video",                  Component: PauseCircle },
];

export function searchIcons(query: string, limit = 120): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ICON_LIBRARY.slice(0, limit);
  const matched = ICON_LIBRARY.filter(
    (i) => i.name.includes(q) || i.keywords.includes(q),
  );
  return matched.slice(0, limit);
}
